---
- name: Update APT cache
  apt:
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: dist

- name: Install common packages
  apt:
    name:
      - git
      - curl
      - htop
    state: present
